### ISSUE TITLE
Issue with tm_shape

### ISSUE THREAD

**Issue by leigh32michael** [DS4PS/ddmp-uw-class-spring-2019#11]
Hi all,

I'm experiencing what I think is a really simple error, but I can't find a solution. 
(I ran into this issue in the lab last week, too and figured out some workaround, but now I can't remember what I did to get it right.)

I've copied Eric's code for the lab into a new R markdown. I changed the output so that it pulls data from my downloaded Seattle pet licensing file ("/Users/lmichael/Desktop/LM/Seattle_Pet_Licenses.csv")

But when I knit the code, all is well until the chunk starting at line 78:
<img width="839" alt="Screen Shot 2019-05-19 at 12 47 00 PM" src="https://user-images.githubusercontent.com/50807806/57987289-3950de80-7a34-11e9-97fe-ec0c55669e60.png">

I get this error message: 
<img width="958" alt="Screen Shot 2019-05-19 at 12 47 47 PM" src="https://user-images.githubusercontent.com/50807806/57987294-4cfc4500-7a34-11e9-9ea5-2fa88345fb4e.png">

I have installed the tmap package (install.packages("tmap")), so I don't understand why the action halts when I try to call the function "tm_shape."

I'd really appreciate any advice! I'm at a bit of a stall with the lab until I can get the original to successfully load.. Thank you!

**Comment by ejvanholm** [comment]
Do you need to add library(tmap) so the function is loaded when you knit?

**Comment by leigh32michael** [comment]
*palm to forehead* — you've got it. Thank you!
